<section class="invoice" style="width: 70%; margin: 0 auto;"">
	

	<div class="row">
		<div class="col-md-12">

	  		<a type="button" href="<?php echo $this->url(array('controller' => 'asignacion', 'action' => 'consulta')); ?>" class="btn btn-primary btn-flat" >
	    		<i class="fa fa-arrow-left"></i> Volver
	  		</a>

		</div>
	</div>

	</br>

	<div class="box">
		 <div class="box-header bg-orange">
		  	<h3 class="box-title">
		      	<i class="fa fa-user"></i> Informacion de Analista
		  	</h3>
    	</div>

    	<div class="box-body">

    		<table class="table table-striped table-bordered">
                <tbody>
                <tr>
                  <td class="col-md-3"><b>Ficha</b></td>
                  <td><?php echo $this->analista->ficha?></td>
                </tr>
                <tr>
                  <td class="col-md-3"><b>Cedula</b></td>
                  <td><?php echo $this->analista->cedula?></td>
                </tr>
                <tr>
                  <td class="col-md-3"><b>Nombre</b></td>
                  <td><?php echo $this->analista->nombre." ".$this->analista->apellido ?></td>
                </tr>
              </tbody>
          </table>

    	</div>
	</div>

	<div class="box">

    	<div class="box-header bg-orange">
		  	<h3 class="box-title">
		      	<i class="fa fa-plus"></i> Asignar Pedido
		  	</h3>
    	</div>

		<div class="box-body">

			<form class="col-md-12" action="#" method="post">
			
				<div class="input-group" >

					<div>
						<?php echo $this->formulario->getElement(Application_Form_AsignarPedido::E_NRO_PEDIDO)->renderViewHelper(); ?>
						<span class="input-group-btn">
						  	<?php echo $this->formulario->getElement(Application_Form_AsignarPedido::E_ASIGNAR)->renderViewHelper(); ?>
						</span>
					</div>

				</div>

	          	<div class="input-group" style="display: none;">
	    			<?php echo $this->formulario->getElement(Application_Form_AsignarPedido::E_CEDULA_ANALISTA)->setValue($this->analista->cedula); ?>
	    			<?php echo $this->formulario->getElement(Application_Form_AsignarPedido::E_CEDULA_JEFE)->setValue($this->jefe->cedula); ?>
    			</div>

			</form>
		</div>

	</div>


  	<div class="box">

    	<div class="box-header bg-orange">
		  	<h3 class="box-title">
		      	<i class="fa fa-list-ol"></i> Asignaciones
		  	</h3>
    	</div>

    	<div class="box-body">
	        <div class="table-responsive" >
	          	<table id="asignaciones" class="table table-striped table-bordered">
		            <thead class="bg-gray">
			            <tr>
			            	<th>Numero de pedido</th>
			            	<th>Asignado por</th>
			              	<th>Fecha de asignacion</th>
			              	<th>Opción</th>
			            </tr>
		            </thead>
		            <tbody>
		            </tbody>
	          	</table>
	        </div>
    	</div>

  	</div>

</section>

<!------SCRIPTS------>
<script type="text/javascript">

	/*funcion para los campos que sean solo digitos o numeros*/
	function validarDigitos(evt){
		var charCode = (evt.which) ? evt.which : event.keyCode
		if (charCode > 31 && (charCode < 48 || charCode > 57))
		return false;

		return true;
    }

	$(document).ready(
  		function() {
	        $('#asignaciones').DataTable({
	          	language: {
		            "decimal": "",
		            "emptyTable": "No existen asignaciones",
		            "info": "<pre>Mostrando _START_ a _END_ de <b>_TOTAL_</b> Asignaciones</pre>",
		            "infoEmpty": "<pre>Mostrando 0 a 0 de <b>0</b> Asignaciones</pre>",
		            "infoFiltered": "(Filtrado de _MAX_ total Asignaciones)",
		            "infoPostFix": "",
		            "thousands": ",",
		            "lengthMenu": "Mostrar _MENU_ Asignaciones",
		            "loadingRecords": "Cargando...",
		            "processing": "Procesando...",
		            "search": "Buscar",
		            "zeroRecords": "No existen asignaciones",
		            "paginate": {
		                "first": "Primero",
		                "last": "Ultimo",
		                "next": "Siguiente",
		                "previous": "Anterior"
		            }
	          	},
          		lengthChange: false,
	          	ajax: {
	            	url: '<?php echo $this->url(array('controller' => 'ajax', 'action' => 'getasignaciones', 'cedula' => $this->analista->cedula)); ?>',
	            	dataSrc: '',
	          	},
	          	columns: [
		            { 	
		            	data: 'nro_pedido',
		            	className: 'text-center',
		              	orderable: false
		        	},
		            { 	
		            	data: 'asignado_por',
		            	className: 'text-center',
		              	orderable: false
		        	},
		            { 	
		            	data: 'fch_asignacion',
		            	className: 'text-center',
		              	orderable: false
		        	},	          	
                    {
		              	data: 'nro_pedido',
		              	className: 'text-center',
		              	orderable: false,
		              	render: function (data, type, row, meta) { //Solo importa data

		                	return '<form method="POST" action="#" role="form">'+
		                		'<a class="fa fa-compass fa-2x" title="Ver seguimiento" href="../pedido/seguimiento?id='+data+'"></a>'+
							  	'<input type="hidden" id="txtPedido" name="txtPedido" value="'+row.nro_pedido+'">'+
							  	'<input type="hidden" id="txtAnalista" name="txtAnalista" value="'+row.asignado_a+'">'+
							  	'<button type="submit" id="btnDesasignar" name="btnDesasignar" style="background: none; padding: 0px; border: none; ">'+
							  	'<i class="fa fa-close fa-2x" ></i>'+
							  	'</button>'+
							'</form>';
		                	
		              	}
		            }
	          	],
	          	order: [[0, 'asc']]
	        });

	    }
    );

</script>