<div class="box">
  <!-- box-header -->
  <div class="box-header bg-orange">
    <h3 class="box-title"><b>LISTADO DE PEDIDOS NACIONALES</b></h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body table-responsive" style="width: 99%;">

    <table id="pedidos" class="display general table-hover table-striped table-bordered nowrap compact">
      <thead class="bg-gray">
        <tr>
          <th class="text-center">Documento de compras</th>
          <th class="text-center">Fecha de Documento</th>
          <th class="text-center">Descripción</th>
          <th class="text-center">Posiciones</th>
          <th class="text-center">Proveedor</th>
          <th class="text-center">Estado</th>
          <th class="text-center">Opciones</th>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
  
  <!-- /.box-body -->
</div>

<script>
  jQuery.extend( jQuery.fn.dataTableExt.oSort, {
    "date-uk-pre": function ( a ) {
        var ukDatea = a.split('/');
        return (ukDatea[2] + ukDatea[1] + ukDatea[0]) * 1;
    },

    "date-uk-asc": function ( a, b ) {
        return ((a < b) ? -1 : ((a > b) ? 1 : 0));
    },

    "date-uk-desc": function ( a, b ) {
        return ((a < b) ? 1 : ((a > b) ? -1 : 0));
    }
  });

  $(document).ready(function() {
        $('#pedidos').DataTable({
          language: {
              "decimal": "",
              "emptyTable": "No hay información",
              "info": "<pre>Mostrando _START_ a _END_ de <b>_TOTAL_</b> Registros</pre>",
              "infoEmpty": "<pre>Mostrando 0 a 0 de <b>0</b> Registros</pre>",
              "infoFiltered": "(Filtrado de _MAX_ total entradas)",
              "infoPostFix": "",
              "thousands": ",",
              "lengthMenu": "Mostrar _MENU_ Entradas",
              "loadingRecords": "Cargando...",
              "processing": "Procesando...",
              "search": "Buscar",
              "zeroRecords": "Sin información encontrada",
              "paginate": {
                  "first": "Primero",
                  "last": "Ultimo",
                  "next": "Siguiente",
                  "previous": "Anterior"
              }
          },
          ajax: {
            url: '<?php echo $this->url(array('controller' => 'ajax', 'action' => 'getpedidosnacionales')); ?>',
            dataSrc: '',
          },
          columns: [
            { 
              data: 'numero_documento',
              className: 'text-center'
            },
            {
              data: 'fecha_documento',
              className: 'text-center',
              type: 'date-uk'
            },
            { data: 'texto_breve'},
            { 
              data: 'renglones',
              className: 'text-center'
            },
            { data: 'proveedor'},
            { 
              data: 'estado',
              className: 'text-center'
            },
            {
              data: 'numero_documento',
              className: 'text-center',
              orderable: false, 
              render: function (data, type, row, meta) {
                return '<a class="fa fa-compass fa-2x" href="seguimiento/id/'+data+'" title="Ver seguimiento"></a>';
              }
            }
            
          ]
        });
    });
</script>
