<br>
<br>
<br>
<br>
<div class="row">
    <div class="col-md-6">
      <div class="box" style="left: 50%;">     	
        <div class="box-header bg-orange" style="text-align: center"> 
          	<h3 class="box-title"><b>ESTADO DE SOLICITUD</b></h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
          	<table id="estados" class="table table-hover" >
	            <thead >
		            <tr >
		            	<th style="text-align: center">
		            		<span class="hint">Haga click en cualquier proceso para ver la información.</span>
		            	</th>
		            </tr>
	            </thead>
	            <tbody >
		            <tr class="detalles-solp">
		            	<td style="text-align: center"><b>Proceso de Solicitud de Pedido</b></td>
		            </tr>
		            <tr class="detalles-pedido">
		            	<td style="text-align: center"><b>Proceso de Pedido de Compras</b></td>
		            </tr>
	            </tbody>
          	</table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
</div>



<script>

	function dataSolp() {
		return '<div class="box-body table-responsive ">'+
			'<table class="table table-hover">'+
		        '<tr style="border-bottom: 1px solid #EEE;">'+
		            '<td ><b>Numero de solicitud:</b></td>'+
		            '<td ><?php echo $this->infosolp->nro_solp ?></td>'+
		        '</tr>'+
		        '<tr style="border-bottom: 1px solid #EEE;">'+
		            '<td ><b>Tipo:</b></td>'+
		            '<td ><?php echo $this->infosolp->departamento ?></td>'+
		        '</tr>'+
		        '<tr style="border-bottom: 1px solid #EEE;">'+
		            '<td ><b>Estado:</b></td>'+
		            '<td ><?php echo $this->infosolp->estado_solp ?></td>'+
		        '</tr>'+
		        '<tr style="border-bottom: 1px solid #EEE;">'+
		            '<td ><b>Fecha de liberacion:</b></td>'+
		            '<td ><?php echo $this->infosolp->fch_lib_pedido ?></td>'+
		        '</tr>'+	        
	    	'</table>'
    	'</div>';
	}

	function dataPedido(){
		return '<div class="box-body table-responsive ">'+
			'<table class="table table-hover style="background-color: solid #DDD;">'+
				'<tbody>'+
			        '<tr style="border-bottom: 1px solid #EEE;">'+
			            '<td ><b>Numero de documento:</b></td>'+
			            '<td ><?php if($this->infopedido) echo $this->infopedido->nro_pedido ?></td>'+
		        	'</tr>'+
			        '<tr style="border-bottom: 1px solid #EEE;">'+
			            '<td ><b>Fecha de creacion del documento:</b></td>'+
			            '<td ><?php if($this->infopedido) echo $this->infopedido->fch_creacion_pedido ?></td>'+
			        '</tr>'+
			        '<tr style="border-bottom: 1px solid #EEE;">'+
			            '<td ><b>Estado de pedido:</b></td>'+
			            '<td ><?php if($this->infopedido) echo $this->infopedido->estado_pedido ?></td>'+
			        '</tr>'+
			        '<tr style="border-bottom: 1px solid #EEE;">'+
			            '<td ><b>Modalidad:</b></td>'+
			            '<td ><?php if($this->infopedido) echo $this->infopedido->modalidad ?></td>'+
			        '</tr>'+
		        '<tbody>'+
		    '</table>'+
		    '<table class="table table-hover">'+  
		    	'<thead>'+
			        '<tr style="text-align: center; border-bottom: 1px solid #EEE;">'+
						'<th style="text-align: center;">Nivel Liberación</th>'+
						'<th style="text-align: center;">Fecha Liberación</th>'+
					'</tr>'+
				'</thead>'+
				'<tbody>'+
				<?php if($this->infopedido) if($this->infopedido->lib_cargo_n1):?>
			        '<tr style="border-bottom: 1px solid #EEE;">'+
			            '<td style="text-align: center;"><?php echo $this->infopedido->lib_cargo_n1?></td>'+
			            '<td style="text-align: center;"><?php echo $this->infopedido->lib_fecha_n1?></td>'+
			        '</tr>'+
		     	<?php endif ?>
				<?php if($this->infopedido) if($this->infopedido->lib_cargo_n2):?>
			        '<tr style="border-bottom: 1px solid #EEE;">'+
			            '<td style="text-align: center;"><?php echo $this->infopedido->lib_cargo_n2?></td>'+
			            '<td style="text-align: center;"><?php echo $this->infopedido->lib_fecha_n2?></td>'+
			        '</tr>'+
			     <?php endif ?>
 				<?php if($this->infopedido) if($this->infopedido->lib_cargo_n3):?>
			        '<tr style="border-bottom: 1px solid #EEE;">'+
			            '<td style="text-align: center;"><?php echo $this->infopedido->lib_cargo_n3?></td>'+
			            '<td style="text-align: center;"><?php echo $this->infopedido->lib_fecha_n3?></td>'+
			        '</tr>'+
			     <?php endif ?>
 				<?php if($this->infopedido) if($this->infopedido->lib_cargo_n4):?>
			        '<tr style="border-bottom: 1px solid #EEE;">'+
			            '<td style="text-align: center;"><?php echo $this->infopedido->lib_cargo_n4?></td>'+
			            '<td style="text-align: center;"><?php echo $this->infopedido->lib_fecha_n4?></td>'+
			        '</tr>'+
			     <?php endif ?>
 				<?php if($this->infopedido) if($this->infopedido->lib_cargo_n5):?>
			        '<tr style="border-bottom: 1px solid #EEE;">'+
			            '<td style="text-align: center;"><?php echo $this->infopedido->lib_cargo_n5?></td>'+
			            '<td style="text-align: center;"><?php echo $this->infopedido->lib_fecha_n5?></td>'+
			        '</tr>'+
			     <?php endif ?>
		        '</tbody>'+		        
	    	'</table>'
    	'</div>';

	}

	$(document).ready(
  		function() {
	        var estados = $('#estados').DataTable({
	          	language: {
		            "decimal": "",
		            "emptyTable": "No hay información",
		            "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
		            "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
		            "infoFiltered": "(Filtrado de _MAX_ total entradas)",
		            "infoPostFix": "",
		            "thousands": ",",
		            "lengthMenu": "Mostrar _MENU_ Entradas",
		            "loadingRecords": "Cargando...",
		            "processing": "Procesando...",
		            "search": "Buscar",
		            "zeroRecords": "Sin información encontrada",
		            "paginate": {
		                "first": "Primero",
		                "last": "Ultimo",
		                "next": "Siguiente",
		                "previous": "Anterior"
		            }
	          	},
	          	lengthChange: false,
	          	searching: false,
	          	ordering: false,
	          	bInfo: false,
	          	paging: false
	        });

		    $('#estados tbody').on('click', 'tr.detalles-solp', function () {
		        var tr = $(this).closest('tr');
		        var row = estados.row( tr );
		 
		        if ( row.child.isShown() ) {
		            // This row is already open - close it
		            row.child.hide();
		            tr.removeClass('shown');
		        }
		        else {
		            // Open this row
		            row.child(dataSolp()).show();
		            tr.addClass('shown');
		        }
		    });

		    $('#estados tbody').on('click', 'tr.detalles-oferta', function () {
		        var tr = $(this).closest('tr');
		        var row = estados.row( tr );
		 
		        if ( row.child.isShown() ) {
		            // This row is already open - close it
		            row.child.hide();
		            tr.removeClass('shown');
		        }
		        else {
		            // Open this row
		            row.child(dataOferta()).show();
		            tr.addClass('shown');
		        }
		    });

		    $('#estados tbody').on('click', 'tr.detalles-pedido', function () {
		        var tr = $(this).closest('tr');
		        var row = estados.row( tr );
		 
		        if ( row.child.isShown() ) {
		            // This row is already open - close it
		            row.child.hide();
		            tr.removeClass('shown');
		        }
		        else {
		            // Open this row
		            row.child(dataPedido()).show();
		            tr.addClass('shown');
		        }
		    });

	    }
    );
</script>